[package]
name = "prophet-rs"
version = "0.1.0"
authors = ["deft"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
read_input = "0.8.4"
